### ISSUE TITLE
Deprecated: Use of BaseTemplate::getFooterIcons was deprecated in MediaWiki 1.35

### ISSUE THREAD

**Issue by jdlrobson** [Dialexio/Jony#11]
( ! ) Deprecated: Use of BaseTemplate::getFooterIcons was deprecated in MediaWiki 1.35. [Called from JonyTemplate::execute in /vagrant/mediawiki/skins/Dialexio-Jony/Jony/JonyTemplate.php at line 134] in /vagrant/mediawiki/includes/debug/MWDebug.php on line 376

This method will likely be removed in either 1.37 or 1.38. To avoid the skin breaking we'll need to fix this. Can help if necessary :)

**Comment by Dialexio** [comment]
Sorry for the delayed response! I'm afraid I don't have much time to continue working on this theme, but I will be more than happy to review and accept pull requests.

**Comment by jdlrobson** [comment]
Great!
